dist: bionic
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - GATK_PATH="$CACHE_DIR"
  - PYTHONIOENCODING=UTF8
  
  - DOCKER_REGISTRY="quay.io"
  - DOCKER_REPO_PROD="quay.io/broadinstitute/viral-core"
  - DOCKER_REPO_DEV="quay.io/broadinstitute/viral-core"
  
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis
  - _JAVA_OPTIONS="-Xmx3g" # overrides jvm opts set elsewhere; see: https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 1000

jobs:
  fast_finish: true
  include:

    - language: generic
      stage: build
      addons:
        apt:
          packages:
          - docker-ce
      env:
        - TRAVIS_JOB=build_docker
        # DOCKER_USER
        - secure: "qS+xuea1oqdV/DLpjaL1Lk1Z7rNTKoaFc7nYvuoOTeNPc6n2kg9MyZYbfu2P/QOPAvK/cuMlTRKWR1MHUO+8PEa4JRBWITVJ9u9Bine9EHbpYl9tEmjrEt9ZWleJRlmGRi5XwVeg49XW9H2CajhCDEQXKOZtsR8kb22T/uLW0TjlK8FgzzBbPgVGlV7NDqYSkmdZecziJqa67yzlC3yTcNc/ZF3sMBP6tDog/V3U+fRvTKVnntp15X/wOnwny71LIt4LBHpCgb0iR7amG/oDMx6RRtUxlJ3pGzGnmhmuWmf3bpo827DVJQi9KADtQ74+BPX1EcOZe5wsnwWbBNPZbEVbvU83ng/Fy19c8mDLJNP9r5+fGJmD1VSSiLsPjhtEfTmpP9fEsubBt5dFaBlPTx8FWua1Zid6+NFBJSysW1choJnP/t2z9CBx+HZxSkP5F30wd9PeoqPvet1GNpAeVF8pTEmtp0OOKnjNkw8Z4tWb7Rr5GN2IrC0v36FKz4WoZTr57ClvFcXTt3nI5kfa+9JUC3OqaNSW7TPHXWefJB6U98JJyKvEIVfVndjfCAX4EZfOh813f78cY5C+10V3i/3gPwil5SVPlwUbhQYCHrwDDRgSlENdRQIyiDbb2/Wl6ie/SVeKMUKWvLAaKLtSwKq0hmZMHxS8KsXBQCeokNg="
        # DOCKER_PASS
        - secure: "q/IabIvb8/m/uQg2XVD+2mEE+lFk2XLJp37QxbSBgPtPY7hP7sHKPW9neaFtzfnkhdu9M14emEMK32g/BcmHE7n8DJzc45nZO9Nb7stoGQnHQAJ2//JX911ZnsrWi6rQvQrwflK98iR3hq4TsKE9ZOJHwJZw/ZerBoEXhHoCnJ6QN/a3DRh8cd6aqtq+HoLgZ0E7QcXJ9dtTsjUVp7AWSwUYYlN64FFh6rNuuHe8rX7+z2c0xF5zwZZozaWy77anPkhainbOWtvJUwCsk5ikKdRgkaq6URo4u43/dHYzxgIKrBLR/Rln9pwF/JjP9Y+aIy38PM3IG5FME6uqTDVo+CyVO8URuRrJemFR0R4dKHgBpd+SOF9+iSgUl5CTJgbCCTr97qkSXdIGbmZcW1+gDDk3114B72VVLGK1fOQZyACZkBUBg+Vj2C6IB1q3fHmP2ETozKvSnZN+GVaWdeWwFSO7jVWOD1CgkW2tSvzocvocNN1NA0VFT35zcYZ7SF49422MstooygnZLwlge6VZQ8RzWh/5eKQa2GNC2xqZX23Ljqd7MVYN07if+HSVZ2g4kvegFSm5fTqEVewgMlqQvCkeafncIeEWQm27DfXFN5vgTTS04uW2zRqqvAcD2pD6j4tBausPJgxuSGyfBnL0RXCpblAdLnPwFHcbLJNgabk="
      script:
        - set -e
        - if [ -f "$CACHE_DIR/old-docker-tag.txt" ]; then OLD_DOCKER_TAG=$(cat $CACHE_DIR/old-docker-tag.txt); else OLD_DOCKER_TAG=$DOCKER_REPO_PROD; fi; echo "old docker tag = $OLD_DOCKER_TAG"
        - if docker pull $OLD_DOCKER_TAG; then _CACHE_FROM="--cache-from $OLD_DOCKER_TAG"; else _CACHE_FROM=""; fi
        - docker build -t local/build-container:build $_CACHE_FROM .
        - travis/deploy-docker.sh
      before_cache:
        - travis/list-docker-tags.sh | tail -1 > $CACHE_DIR/old-docker-tag.txt
    
    #- language: java
    #  jdk: openjdk8
    #  stage: build
    #  env:
    #    - TRAVIS_JOB=build_dxWDL
    #    # DX_API_TOKEN (for DNAnexus builds)
    #    - secure: "IPvLIQudIRyUl8iLNLujDig1afV+2v8AtRHpw0LsbL45xr0TvkmqjoHRmkYDnbdEeVdGC91ydLwfLNXcU/Cn7KRuIPE3InYX6VeomVO87aIXUzmmBCdFNGKd6o0u6Q/T+oJxemXwztW9XpKx3yT4RdLj7/zEpXnJm07/mKiquZE="
    #    - DX_PROJECT=project-F856jv809y3VkzyFGkKqX367
    #  install:
    #    - travis/install-wdl.sh
    #  script:
    #    - travis/version-wdl-runtimes.sh
    #    - travis/validate-wdl.sh
    #    - travis/build-dx.sh

    #- language: java
    #  jdk: openjdk8
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=test_cromwell
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #    - travis/install-wdl.sh
    #  script:
    #    - travis/version-wdl-runtimes.sh
    #    - travis/validate-wdl.sh
    #    - travis/tests-cromwell.sh

    - language: python
      stage: test
      env:
        - TRAVIS_JOB=test_py36_in_docker
        - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov broad_utils --cov illumina --cov read_utils --cov reports --cov tools --cov util --cov file_utils"
      install:
        - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
        - docker pull $DOCKER_TAG
        - pip install coveralls==1.1
        - mkdir coverage
      script:
        - docker run -e _JAVA_OPTIONS -e PYTEST_ADDOPTS -v `pwd`/coverage:/coverage -v `pwd`/test:/opt/viral-ngs/source/test $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; pytest test/unit; cp .coverage /coverage'
      after_success:
        - mv coverage/.coverage .
        - coveralls

    #- language: generic
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=build_conda_in_docker
    #    # $ANACONDA_TOKEN for uploading builds to anaconda.org ("broad-viral" channel)
    #    - secure: "cDKRuVUr2NMZk933RHMMYKDCfU2gZfe3VJLNG82zsj47rrfoRzUsDny71v27OuydgjICiBWGuFAl4alNBVkzQWGt7G1DaFVLn48SwqtnG4u0KAUVX32b/0sw7OrXRDDqD5pr5Q8J59xwxSKQmmXFXlMbZpSEeREf8c3Yn6pvm2c="
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #  script:
    #    - docker run -v $GATK_PATH:/gatk -e _JAVA_OPTIONS -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST -e TRAVIS_TAG -e TRAVIS_COMMIT -e ANACONDA_TOKEN --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; travis/install-conda-build.sh; travis/build-conda.sh'

