dist: trusty
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PIP_DIR="$HOME/virtualenv"
  - GATK_PATH="$CACHE_DIR"
  - PYTHONIOENCODING=UTF8
  - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov kmer_utils --cov reports --cov taxon_filter --cov tools --cov util --cov file_utils"
  
  - DOCKER_REGISTRY="quay.io"
  - DOCKER_REPO_PROD="quay.io/broadinstitute/micro-readqc"
  - DOCKER_REPO_DEV="quay.io/broadinstitute/micro-readqc"
  
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis
  - _JAVA_OPTIONS="-Xmx3g" # overrides jvm opts set elsewhere; see: https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 1000

jobs:
  fast_finish: true
  include:

    - language: generic
      stage: build
      addons:
        apt:
          packages:
          - docker-ce
      env:
        - TRAVIS_JOB=build_docker
        # DOCKER_USER
        - secure: hYX8492Wqpq3yqv+eHBV9c6VY8JlUSS8mUDfT1eWNEZF2vw8WrnTt8SrLIPC8etQUk1ZaSI/8XbJQKEr9LRqgvuO07AIv6BxYCg9l9BPHCj6B2YTTPo2qPkPapfvtGVd7PUZcWDUvzvPxJqMveuKVkTnCuuQSWwR68Y/Khxj8UY=
        # DOCKER_PASS
        - secure: QYylIMLvn1op6d//5yBD7KpquNxK/+xxQxIJLXWFgIl08sdT/MvrI6edgm3k8CumS7735eSV6C+KGOkF9JqM12aGUK/3PPckFGY+h/j4zQX26taT+6221ozbzF6hqYk6qm86FT5QVkBFLxsoDvt0Sh+1FPeVsWJf0o9yrLTrj2E=
      #install: travis/upgrade-docker.sh
      script:
        - set -e
        - if [ -f "$CACHE_DIR/old-docker-tag.txt" ]; then OLD_DOCKER_TAG=$(cat $CACHE_DIR/old-docker-tag.txt); else OLD_DOCKER_TAG=$DOCKER_REPO_PROD; fi; echo "old docker tag = $OLD_DOCKER_TAG"
        - if docker pull $OLD_DOCKER_TAG; then _CACHE_FROM="--cache-from $OLD_DOCKER_TAG"; else _CACHE_FROM=""; fi
        - travis_wait docker build -t local/micro-readqc:build $_CACHE_FROM .;
        - travis/deploy-docker.sh
      before_cache:
        - travis/list-docker-tags.sh | tail -1 > $CACHE_DIR/old-docker-tag.txt
    
    #- language: java
    #  jdk: openjdk8
    #  stage: build
    #  env:
    #    - TRAVIS_JOB=build_dxWDL
    #    # DX_API_TOKEN (for DNAnexus builds)
    #    - secure: "IPvLIQudIRyUl8iLNLujDig1afV+2v8AtRHpw0LsbL45xr0TvkmqjoHRmkYDnbdEeVdGC91ydLwfLNXcU/Cn7KRuIPE3InYX6VeomVO87aIXUzmmBCdFNGKd6o0u6Q/T+oJxemXwztW9XpKx3yT4RdLj7/zEpXnJm07/mKiquZE="
    #    - DX_PROJECT=project-F856jv809y3VkzyFGkKqX367
    #  install:
    #    - travis/install-wdl.sh
    #  script:
    #    - travis/version-wdl-runtimes.sh
    #    - travis/validate-wdl.sh
    #    - travis/build-dx.sh

    #- language: java
    #  jdk: openjdk8
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=test_cromwell
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #    - travis/install-wdl.sh
    #  script:
    #    - travis/version-wdl-runtimes.sh
    #    - travis/validate-wdl.sh
    #    - travis/tests-cromwell.sh

    - language: python
      stage: test
      env:
        - TRAVIS_JOB=test_py36_in_docker
      install:
        - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
        - docker pull $DOCKER_TAG
        - travis/install-gatk.sh
        - pip install coveralls==1.1
        - mkdir coverage
      script:
        - docker run -e _JAVA_OPTIONS -e PYTEST_ADDOPTS -v $GATK_PATH:/gatk -v coverage:/coverage --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; pytest test/unit; cp .coverage /coverage'
      after_success:
        - mv coverage/.coverage .
        - coveralls

    #- language: generic
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=build_conda_in_docker
    #    # $ANACONDA_TOKEN for uploading builds to anaconda.org ("broad-viral" channel)
    #    - secure: "cDKRuVUr2NMZk933RHMMYKDCfU2gZfe3VJLNG82zsj47rrfoRzUsDny71v27OuydgjICiBWGuFAl4alNBVkzQWGt7G1DaFVLn48SwqtnG4u0KAUVX32b/0sw7OrXRDDqD5pr5Q8J59xwxSKQmmXFXlMbZpSEeREf8c3Yn6pvm2c="
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #  script:
    #    - docker run -v $GATK_PATH:/gatk -e _JAVA_OPTIONS -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST -e TRAVIS_TAG -e TRAVIS_COMMIT -e ANACONDA_TOKEN --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; travis/install-conda-build.sh; travis/build-conda.sh'


