dist: trusty
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PIP_DIR="$HOME/virtualenv"
  - GATK_PATH="$CACHE_DIR"
  - PYTHONIOENCODING=UTF8
  - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov kmer_utils --cov reports --cov taxon_filter --cov tools --cov util --cov file_utils"
  
  - DOCKER_REGISTRY="quay.io"
  - DOCKER_REPO_PROD="quay.io/broadinstitute/micro-readqc"
  - DOCKER_REPO_DEV="quay.io/broadinstitute/micro-readqc"
  
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis
  - _JAVA_OPTIONS="-Xmx3g" # overrides jvm opts set elsewhere; see: https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 1000

jobs:
  fast_finish: true
  include:

    - language: generic
      stage: build
      addons:
        apt:
          packages:
          - docker-ce
      env:
        - TRAVIS_JOB=build_docker
        # DOCKER_USER
        - secure: "l4Nzzsjeh6VqwbkN4a8nKcNPbwYjysjmlZsrCW/HcXqdC+r+K/C1y5TLNUHxomEj4dCkCkLXYmUar0l4UmdVGbfMnNlRxbZ5mRSho1HujENGXK38Ak2yEJtjUzqDoKB3etFtaCT/iqR4QUG1BXWD7VV0MSruQI5wV+Rzchaxqfu/QQkorgWSkQkPLPjTz0EmomRasVmqFe/ex52i53TR7bJJTULAy9+Df2IJlM877XlH3BJ9S+zqxjKX247m/eFLcA5vV5YiQ6244c8xVlgZhRD7On++ypc79JNhN7WmIl4HySBMy5HEf6YWevAmju0IhHZCfZsYTZ2SPvyuw3kth6ig5W89UrcZ1/guYazDnLRyk0aNiYNiovFXLIxrZlIWNSbHhOn/TV/ZHtuab76e9cMFNIAx7LjzgrpEoywU8b3Zn4IOJvd5t+PHTlBdHUh/LPsXUiwYHj1OFyuDFh5JjN7a6S+7/p/9Myab8fY0CyGRBBbIs0v29Aup3QGmaUjpKesGOM+QTpouQXlIYcTVFHTRQBi1ZFsMjCUf4Udu9GyrdJu+xfjQ17UBWdyWLq6G/btD7pvPIjO64eTQOCXr/60noagy7whP9Nnm5p9eWQnTZCuJZYeQLS0QC3FUAE0WMnN47B0CTTmBDZwMbaAqDMR1ZExqP1iJeDKnjtUqpdg="
        # DOCKER_PASS
        - secure: "M+xATe/gbZYb1vdUl81xnZbk+xKtDe8n5E+kPjAX0a7j1FblNgPHkYVPxjn3xHAwJ26risWgC/cKeE+UYEs7qDXeC14FYBQYaHXDpwlJ+DaYbNtZ4vKeD/EX3IUr1YHiIvRehBTcT+HRATe62FpEg7VcK8cWIZk8l158BOpPwDNi2qbx1hxa2jp9GKVa5Z69RdIi/Jh4FJTd5l12lL00rJSkT2HfuMs3LsWbULZGrh6p0wSd2ZyFnqfmXIYG7toiEwzYuCfOnhN8P86miGYwIkwPDxcldLUESUGWMhun2gCmtdChDtUOVT1KRguDhLFpuQ5ZI8WOiM3yCA46/znSSXFvX1vgfLYpgb8Gomz+AaOhHpG7FyX2C79FbqEL9+pAqQeUYUYOokydD2lbPA5IF8BD/CT/AtOIGxyuuCth1yI0/568DYOOr+bQ0jcEeeQPBbIrZulioAApG3pCKRWbwj8igRKEXk/aMOHtxIY6+JRgTpllKf0zlXJniM4mQJ4i+8FBHz7NYUJKM+2BAe7OnkGFd5k9p0blpM6jhkM50/qHHorUpEQnXRnlfpOO5PX07Ka2o0E0kxX8pdI/KzwuX9cRDPTzGn2bbHSQyqvWvGn94IzezhH3FFFyRofRFCcbEvsvAvd010tS7xcAEv5rVow6ck+knbAoH+RzIfMnNhk="
      #install: travis/upgrade-docker.sh
      script:
        - set -e
        - if [ -f "$CACHE_DIR/old-docker-tag.txt" ]; then OLD_DOCKER_TAG=$(cat $CACHE_DIR/old-docker-tag.txt); else OLD_DOCKER_TAG=$DOCKER_REPO_PROD; fi; echo "old docker tag = $OLD_DOCKER_TAG"
        - if docker pull $OLD_DOCKER_TAG; then _CACHE_FROM="--cache-from $OLD_DOCKER_TAG"; else _CACHE_FROM=""; fi
        - travis_wait docker build -t local/build-container:build $_CACHE_FROM .;
        - travis/deploy-docker.sh
      before_cache:
        - travis/list-docker-tags.sh | tail -1 > $CACHE_DIR/old-docker-tag.txt
    
    #- language: java
    #  jdk: openjdk8
    #  stage: build
    #  env:
    #    - TRAVIS_JOB=build_dxWDL
    #    # DX_API_TOKEN (for DNAnexus builds)
    #    - secure: "IPvLIQudIRyUl8iLNLujDig1afV+2v8AtRHpw0LsbL45xr0TvkmqjoHRmkYDnbdEeVdGC91ydLwfLNXcU/Cn7KRuIPE3InYX6VeomVO87aIXUzmmBCdFNGKd6o0u6Q/T+oJxemXwztW9XpKx3yT4RdLj7/zEpXnJm07/mKiquZE="
    #    - DX_PROJECT=project-F856jv809y3VkzyFGkKqX367
    #  install:
    #    - travis/install-wdl.sh
    #  script:
    #    - travis/version-wdl-runtimes.sh
    #    - travis/validate-wdl.sh
    #    - travis/build-dx.sh

    #- language: java
    #  jdk: openjdk8
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=test_cromwell
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #    - travis/install-wdl.sh
    #  script:
    #    - travis/version-wdl-runtimes.sh
    #    - travis/validate-wdl.sh
    #    - travis/tests-cromwell.sh

    - language: python
      stage: test
      env:
        - TRAVIS_JOB=test_py36_in_docker
      install:
        - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
        - docker pull $DOCKER_TAG
        - travis/install-gatk.sh
        - pip install coveralls==1.1
        - mkdir coverage
      script:
        - docker run -e _JAVA_OPTIONS -e PYTEST_ADDOPTS -v $GATK_PATH:/gatk -v coverage:/coverage --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; pytest test/unit; cp .coverage /coverage'
      after_success:
        - mv coverage/.coverage .
        - coveralls

    #- language: generic
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=build_conda_in_docker
    #    # $ANACONDA_TOKEN for uploading builds to anaconda.org ("broad-viral" channel)
    #    - secure: "cDKRuVUr2NMZk933RHMMYKDCfU2gZfe3VJLNG82zsj47rrfoRzUsDny71v27OuydgjICiBWGuFAl4alNBVkzQWGt7G1DaFVLn48SwqtnG4u0KAUVX32b/0sw7OrXRDDqD5pr5Q8J59xwxSKQmmXFXlMbZpSEeREf8c3Yn6pvm2c="
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #  script:
    #    - docker run -v $GATK_PATH:/gatk -e _JAVA_OPTIONS -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST -e TRAVIS_TAG -e TRAVIS_COMMIT -e ANACONDA_TOKEN --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; travis/install-conda-build.sh; travis/build-conda.sh'


